### ISSUE TITLE
GH: SchemaBuilder can generate invalid BuiltElements

### ISSUE THREAD

**Issue by AlanRynne** [specklesystems/speckle-sharp#398] opened 2021-03-26 09:06 UTC
Currently, the `SchemaBuilder` node in Grasshopper doesn't validate data in any way, meaning that if `null` values are passed, it will still properly generate a `Base` object, but that object would be invalid upon reception.

See screenshot, generating a family instance with null points still generates the output objects, though it shouldn't.

![Screenshot 2021-03-26 at 10 02 08](https://user-images.githubusercontent.com/2316535/112608778-04c1c100-8e1b-11eb-8e6c-9727e4c373f6.png)

We could go about it in 2 ways:

- Either we select the correct parameter type when creating the node inputs, as they currently accept any type.
- Add validation of data when creating objects using `SchemaBuilder` and return null for entities that are not correct.

Maybe we should do both....

**Comment by teocomi** [comment] 2021-03-26 14:47
Duplicate of https://github.com/specklesystems/speckle-sharp/issues/230 although I consider it an enhancement ;P

**Comment by AlanRynne** [comment] 2021-03-26 15:38
Hmmm... the validation proposed in #230 would be an enhancement, but what happens here is clearly a bug imho. As a family instance with a `null` point should never be created, or a beam with a `null` line; as opposed to creating a beam with a valid line that just happens to be too small.


Granted, they are linked problems for sure. ldeally, the behaviour of this would be the same as the `CreateSpeckleObject` node.

![Screenshot 2021-03-26 at 16 36 53](https://user-images.githubusercontent.com/2316535/112656225-79afed80-8e51-11eb-8641-e38040546346.png)

**Comment by didimitrie** [comment] 2021-07-23 14:43
Closing as stale. I'm pretending to be a bot; will reopen when we have the bandwidth.

**Closed by didimitrie** 2021-07-23 14:43 UTC
Labels: bug, grasshopper, p3
