### ISSUE TITLE
Missing geometry when sending from Grasshopper

### ISSUE THREAD

**Issue by paloknapo** [specklesystems/speckle-sharp#2059] opened 2023-01-10 08:55 UTC
## What package are you referring to?
Grasshopper Connector 2.11

## Describe the bug
Missing vertical elements in a railing model. 

## To Reproduce

1. Open [this test file](https://drive.google.com/file/d/12SxlArkZcJNpQZRkScAUTuiSHkqZG5nT/view?usp=share_link ) in Grasshopper
2. Send
3. See results in[ this stream ](https://latest.speckle.dev/streams/82592d1f8d/branches/bug report)

## Expected behaviour
Import full model with all elements. 

## Screenshots
Grasshopper 
![image](https://user-images.githubusercontent.com/760452/211504036-5fa98d2a-aa31-464c-91ed-1d207251a041.png)
Speckle
https://latest.speckle.dev/streams/82592d1f8d/commits/6bb1de680f
![image](https://user-images.githubusercontent.com/760452/211504083-66499d01-158c-48b3-a276-e03bb0251cb5.png)

### Desktop (please complete the following information):

- OS: Windows
- Browser Firefox

**Comment by AlanRynne** [comment] 2023-01-12 10:27
This is not a bug. At least, not one coming from Grasshopper :)

All the data seems to be there, but you've modelled them as `Box` instances, and the viewer ignores all `Box` instances as they're used on every object to hold their bounding box.

![Screenshot 2023-01-12 at 11 14 44](https://user-images.githubusercontent.com/2316535/212040426-69035caf-28a4-4c52-9ed0-dfc7fcb6d8af.png)

If you convert the boxes into breps/meshes, they will show up.

https://latest.speckle.dev/streams/82592d1f8d/commits/878bd0b975

Receiving the commit you shared back in GH also works as expected
![Screenshot 2023-01-12 at 11 25 27](https://user-images.githubusercontent.com/2316535/212042358-83a1bde3-3ab6-4c29-8079-3d55a0be10f1.png)

There is an issue though with the `Box` class, if you try to receive the commit you provided in a different unit, boxes will not show up (I think its a transform problem), I'll open a separate issue for this.

**Comment by paloknapo** [comment] 2023-01-13 07:03
That box doesn't make it to Rhino or SketchUp so if basic geometry doesn't make it to other applications, I would still insist it's a interoperability bug :)

![Image](https://user-images.githubusercontent.com/760452/212257656-6bda245b-d426-49bc-817b-bece5ef471d5.png)

![Image](https://user-images.githubusercontent.com/760452/212257703-92c28a40-b0ae-47b4-8e6b-38f23105733c.png)

**Comment by AlanRynne** [comment] 2023-01-13 10:08
> I would still insist it's a interoperability bug :)

Agreed, but my prior reply still stands.

> This is not a bug. At least, not one coming from Grasshopper :)

As the issue was described, it was assumed that Grasshopper was not sending those boxes, which is not really what is happening as GH deals with them as expected, and the boxes do exist in the commit.

Not sure about Sketchup but Rhino should has support for `Box->Rhino` conversions ( I just checked in the code ), so there may be a bug in the way Rhino handle's these when baking to the document (not when converting, as the logic is the same used in GH)

@clairekuang can you confirm this is the case?

**Comment by AlanRynne** [comment] 2023-01-13 10:23
Just had a quick chat with @oguzhankoral and in Sketchup, `Box` instances are ignored when received. So it should be a matter of adding them to the conversion routine.

**Comment by AlanRynne** [comment] 2023-03-06 10:35
Closing this as a non-issue. If boxes need to be supported in other connectors, new issues should be created for this.

**Closed by AlanRynne** 2023-03-06 10:35 UTC
Labels: bug
