### ISSUE TITLE
Speckle Desktop Manager: Problem when uninstall connector

### ISSUE THREAD

**Issue by chuongmep** [specklesystems/speckle-sharp#1871] opened 2022-11-18 00:53 UTC
## Prerequisites

- [x] I read the [contribution guidelines](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)
- [ ] I checked the [documentation](https://speckle.guide/) and found no answer.
- [x] I checked [existing issues](../issues?q=is%3Aissue) and found no similar issue. 
- [ ] I checked the [community forum](https://speckle.community/) for related discussions and found no answer.
- [ ] I'm reporting the issue to the correct repository (see also [speckle-server](https://github.com/specklesystems/speckle-server), [speckle-sharp](https://github.com/specklesystems/speckle-sharp), [specklepy](https://github.com/specklesystems/specklepy), [speckle-docs](https://github.com/specklesystems/speckle-docs), and [others](https://github.com/orgs/specklesystems/repositories))

## Describe the bug

This just a problem when uninstall connector, why uninstall blender request tune off revit software ?

## Screenshots

![image](https://user-images.githubusercontent.com/31106432/202591182-c977e02b-61eb-406b-8b15-321e4450bfe5.png)

## System Info

If applicable, please fill in the below details - they help a lot!

### Desktop (please complete the following information):

Windows 10

## Proposed Solution (if any)

Allow uninstall blender no need tune off revit.

**Comment by AlanRynne** [comment] 2023-02-10 17:01
Hi @chuongmep!

I think we forgot to answer you on this one! We may have been a bit over-zealous on this, but since all Speckle related applications use common libraries, and windows usually locks them while in use, it was decided that we'd make sure any Speckle related app was close before running an update or an uninstall.

Closing this for now bc it's the expected behaviour. If you have any ideas on how to make this better, we'd welcome them with open arms 🤗

**Closed by AlanRynne** 2023-02-10 17:01 UTC
Labels: bug
