### ISSUE TITLE
GH: unexpected Rhino crash.

### ISSUE THREAD

**Issue by iltabe** [specklesystems/speckle-sharp#554] opened 2021-06-09 15:47 UTC
Not sure if this is speckle related or not.
I had 3 GH definitions opened and I was moving around between them.
Then jumping from one definition to anther one, suddenly rhino just crush.

```
[ERROR] FATAL UNHANDLED EXCEPTION: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.WebSockets.InternalClientWebSocket'.
   at System.Net.WebSockets.WebSocketBase.ThrowIfDisposed()
   at System.Net.WebSockets.WebSocketBase.WebSocketOperation.<Process>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.WebSockets.WebSocketBase.<SendAsyncCore>d__47.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GraphQL.Client.Http.Websocket.GraphQLHttpWebSocket.<SendWebSocketMessageAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GraphQL.Client.Http.Websocket.GraphQLHttpWebSocket.<SendWebSocketRequestAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GraphQL.Client.Http.Websocket.GraphQLHttpWebSocket.<>c__DisplayClass27_1`1.<<CreateSubscriptionStream>b__7>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[END ERROR]

**Comment by didimitrie** [comment] 2021-06-09 15:55
From the stack trace, it looks like something thrown by the graphql client lib that we are using. We'll investigate!

**Comment by AlanRynne** [comment] 2021-06-11 16:45
I've had a look at this today. I tried to reproduce it by trashing around with several open files (sending, receiving, swapping active docs...) but can't manage to reproduce it.

It does remind me of a previous bug we fixed months ago related to components receiving notifications even when their document was not active. In that case, we ensured client's were disposed of correctly to prevent this. Not sure if this is directly related though 👀

**Comment by iltabe** [comment] 2021-06-17 10:26
Happend again!
I jumped between definitions where one of the two was receiving.
What I did:

1. Open old definition
2. create new definition
3. Copy paste from old to new these components:
    1. Account
    2. Stream list
    3. Receivers...
    4. Expand speckle object
    2.  
4. In new gh def: I click on receive
5. Jump on old definition
6. FREEZE 
7. CRUSH!

```
[ERROR] FATAL UNHANDLED EXCEPTION: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.WebSockets.InternalClientWebSocket'.
   at System.Net.WebSockets.WebSocketBase.ThrowIfDisposed()
   at System.Net.WebSockets.WebSocketBase.WebSocketOperation.<Process>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.WebSockets.WebSocketBase.<SendAsyncCore>d__47.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GraphQL.Client.Http.Websocket.GraphQLHttpWebSocket.<SendWebSocketMessageAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GraphQL.Client.Http.Websocket.GraphQLHttpWebSocket.<SendWebSocketRequestAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GraphQL.Client.Http.Websocket.GraphQLHttpWebSocket.<>c__DisplayClass27_1`1.<<CreateSubscriptionStream>b__7>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[END ERROR]`

**Comment by AlanRynne** [comment] 2021-06-17 11:02
OH! thanks for this, it will be super useful! I'll try to reproduce your steps and hopefully we can find the culprit of this nasty crash!

If the receiver is still "receiving" while you do the change, we may just need to listen to the proper event and cancel any operations that are on going. GH does not like things happening in "non-active" documents.

**Comment by AlanRynne** [comment] 2021-06-18 07:49
Ok, I managed to reproduce the error a couple times while debugging. I'm going to push a fix in a short while.

Basically, when the `DocumentContext` changed, we were disposing of the `ApiClient` without cancelling any ongoing requests first, hence the explosion. 💥

I'm adding `RequestCancellation()` call when the document get's unloaded, plus an `OnDisplayExpired()` call when the document is loaded again to ensure the UI buttons reflect the cancelled state.

We'll let you know once its merged in :) Not sure if it will go before or after #539.

**Comment by iltabe** [comment] 2021-06-18 08:40
Nice that you managed to reproduce it! :)
No worries about timing. I'm in a quite stable configuration at the moment. I'm not keen on updating Speckle version since I'm delivering fabrication data.
Thanks!

**Closed** 2021-06-18 08:49 UTC
Labels: bug, grasshopper
