### ISSUE TITLE
DUI2 outstanding bugs/fixes

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sharp#821] opened 2021-11-08 16:03 UTC
- [x] show detail on send/receive operation instead of "never sent/last sent ...", actually show progress % and text
- [x] keep window in foreground and make sure it's brought on top when clicking on adding button again (Revit, Rhino) PARTLY implemented, can;t keep the 2 windows in sync unforch
- [x] view online button on saved streams should open the selected branch
- [x] investigate crash in rhino: create new branch online > and hit refresh > dui2 > ?
- [x] add timestamp to reports
- [ ] text size and style of dialogs can be improved

**Comment by clairekuang** [comment] 2021-11-30 21:16
>  investigate crash in rhino: create new branch online > and hit refresh > dui2 > ?
Couldn't reproduce this! might've been resolved with commit selection hotfix from last release

**Comment by teocomi** [comment] 2021-11-30 22:25
Cool, in regards to the last remaining item "text size and style of dialogs can be improved", I think the only simple solution is to make our own dialogs rather than using the built-in modals (which I could not style).
But let's move it to a P3 then!

**Closed** 2021-12-01 13:21 UTC
