### ISSUE TITLE
UI Reports incorrect Speckle version on macos

### ISSUE THREAD

**Issue by fraguada** [specklesystems/speckle-sharp#1910] opened 2022-11-23 15:10 UTC
UI in Rhino for mac reports v2.0.0-dev, while on win it reports the correct version number, v2.10.0-rc3

Windows: 
![image](https://user-images.githubusercontent.com/1014562/203580407-00abe4f0-9bd2-4542-bc7a-105d37b34cba.png)

macos:
![image](https://user-images.githubusercontent.com/1014562/203580605-4141df4a-d63a-40e9-8856-ec0d0aaf0c8e.png)
![image](https://user-images.githubusercontent.com/1014562/203580861-4081e5ba-b3fe-42ec-a470-6e9470bd5dd2.png)

**Comment by teocomi** [comment] 2022-11-23 16:03
@AlanRynne as I don't currently have my mac can you look at this?
It was fixed in the past with https://github.com/specklesystems/speckle-sharp/pull/1800 but something got lost when we had that those merge issues with `main`

**Comment by AlanRynne** [comment] 2022-11-24 09:33
This was definitely caused by our merge issues in `main` prior to start testing 2.10. I've identified the 3 offending commits:

- My merge that broke things 897b714ca1f0cf057da26faad33a56134a499b9e
- The revert operation 31d3e59942e396af36bea4bfc22b6d2f30214a46 aka #1847
- The "fixed" merge, that is missing quite some changes c1a998fa1f026ea7727c34d585496c43111c5c14 aka #1853

**Comment by AlanRynne** [comment] 2022-11-29 08:09
Fixed in #1926 but didn't get closed

**Closed by AlanRynne** 2022-11-29 08:09 UTC
Labels: bug, desktopui, rhino, ✂️ paper-cut, mac
