### ISSUE TITLE
Dynamo for Revit 2023 conflict

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sharp#1753] opened 2022-10-20 12:31 UTC
There seems to be some conflict between our Revit connector and Dynamo in Revit 2023 which makes code blocks uneditable.

Current conversations: 

https://speckle.community/t/dynamo-code-block-not-working-in-revit-2023/3788
https://forum.dynamobim.com/t/code-block-not-working-due-to-conflict/81999

**Comment by AlanRynne** [comment] 2022-11-24 09:04
This seems to be caused by Generative Design plugin for Dynamo. Since it requires more investigating, I'm moving it to 2.11

**Comment by Lazarica-t** [comment] 2023-03-07 14:25
I have the same issue 😢 .. Code blocks are broken even in the latest Revit connector version 2.13

**Comment by Lazarica-t** [comment] 2023-03-08 08:09
@teocomi Yeah... 😕 I don't think it's because of Generative Design. I tried the fixes and none of them worked.
Plus the code blocks don't even work in Dynamo 2.3 in Revit 2020 were there is no Generative Design.
![image](https://user-images.githubusercontent.com/49474519/223656777-43c55860-27e7-4699-96f8-e06bb22f2bc2.png)

**Closed** 2023-10-13 14:07 UTC
Labels: bug, dynamo, revit
